[frame_version]
# true-->启用；false-->禁用
pytorch = true
onnx = true
ascend = false

[retinamodel]
name = "mobilenet0.25"
min_sizes = [[16, 32], [64, 128], [256, 512]]
steps = [8, 16, 32]
variance = [0.1, 0.2]
clip = true
pretrain = true
return_layers = {"stage1"= 1, "stage2"= 2, "stage3"= 3}
in_channel = 32
out_channel = 64
model_path = "resources/models/mobilenet0.25_Final.pth"
pretrained_path = "resources/models/mobilenetV1X0.25_pretrain.tar"

[model_path]
# pytorch_version
retina_torch = "resources/models/mobilenet0.25_Final.pth"
arcface_torch = "resources/models/acc_9737.pth"
# onnx_version
retina_onnx = "resources/models/mobilenet0.25_Final.onnx"
arcface_onnx = "resources/models/acc_9737.onnx"
# ascend_version
retina_om = "resources/models/mobilenet0.25_Final.om"
arcface_om = "resources/models/acc_9737.om"
